### ISSUE TITLE
NullPointerException on MeshDeviceConfigurator.onConnectionStateChanged.

### ISSUE THREAD

**Issue by bisgroves** [paulmandal/atak-forwarder#85] opened 2021-07-18 13:57 UTC
java.lang.NullPointerException

java.lang.NullPointerException: 
  at com.paulmandal.atak.forwarder.comm.meshtastic.MeshDeviceConfigurer.checkOwner (SourceFile:5)
  at com.paulmandal.atak.forwarder.comm.meshtastic.MeshDeviceConfigurer.onConnectionStateChanged (SourceFile:7)
  at com.paulmandal.atak.forwarder.comm.meshtastic.MeshServiceController.a (SourceFile:1)
  at com.paulmandal.atak.forwarder.comm.meshtastic.MeshServiceController.b (Unknown Source)
  at com.paulmandal.atak.forwarder.comm.meshtastic.h.run (Unknown Source:4)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:223)
  at android.app.ActivityThread.main (ActivityThread.java:7656)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:592)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:947)

**Comment by paulmandal** [comment] 2021-10-10 15:15
Can you add reproduction instructions?

**Comment by bisgroves** [comment] 2021-10-10 19:52
Unfortunately not.   I only have the stack trace from Google play.

--
Shawn Bisgrove
PAR Government System Corporation
421 Ridge Street Rome, NY 13440
315.356.2141 (w)
315.571.6767 (c)


This email message and attachment(s) may contain sensitive and/or proprietary information and is intended only for the person(s) to whom this email message is addressed. If you have received this email message in error, please notify the sender immediately and destroy the original message without making a copy. Please do not transmit any sensitive, proprietary, ITARS or FOUO data via e-mail without using approved encryption techniques.

________________________________

**Comment by paulmandal** [comment] 2022-04-14 13:53
Closing since there are no updates.

**Closed by paulmandal** 2022-04-14 13:53 UTC
